### PR TITLE
#175 fixed conversion of empty list to optional

### LINKED ISSUE #175: SET PROPERTY does not refresh metadata from v1.10.0 on
Some properties trigger a refresh of the metadata, e.g. after changing the schema_name:
`ALTER VIRTUAL SCHEMA VS set schema_name='TEST1';`
the metadata should be updated, so that the tables of the new schema are visible.
However the JDBC Adapter v.1.10.0 and later returns empty metadata in this case.

### PR DESCRIPTION
**Pull request by snehlsen**
Table filtering uses Optional and expects empty if no tables are given in the filter (see `BaseTableMetadataReader.isTableSelected()`). However empty lists were not converted to `Optional.empty`.
closes #175

### CODE REVIEW

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReader.java [hunk 1]
```diff
@@ -189,10 +189,18 @@ public SchemaMetadata readRemoteSchemaMetadata(final List<String> selectedTables
...
-            final List<TableMetadata> tables = extractTableMetadata(remoteMetadata, Optional.of(selectedTables));
+            final List<TableMetadata> tables = extractTableMetadata(remoteMetadata, convertToOptional(selectedTables));
             return new SchemaMetadata(adapterNotes, tables);
         } catch (final SQLException exception) {
             throw new RemoteMetadataReaderException("Unable to read remote schema metadata.", exception);
         }
     }
+
+    protected Optional<List<String>> convertToOptional(List<String> selectedTables) {
+        if (selectedTables.size() > 0) {
```
Comment (redcatbear) [inline jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReader.java]:
```
        if ((selectedTables != null) && !selectedTables.isEmpty())) {
```

File: jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReaderTest.java [hunk 2]
```diff
@@ -250,4 +250,15 @@ void testGetSupportedTableTypes() {
         assertThat(new BaseRemoteMetadataReader(null, AdapterProperties.emptyProperties()).getSupportedTableTypes(),
                 containsInAnyOrder("TABLE", "VIEW", "SYSTEM TABLE"));
     }
+
+    @Test
+    void testConvertToOptional() {
```
Comment (redcatbear) [inline jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReaderTest.java]: Use `@ParameterizedTest` with a `@CsvSource` since those are independent test cases. You can then also easily add a NULL test.

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReader.java (hunk 1 above)
Comment (snehlsen) [reply jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReader.java]: done

File: jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReaderTest.java (hunk 2 above)
Comment (snehlsen) [reply jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReaderTest.java]: I will add the NULL test. However `@CsvSource` does not work out of the box becasue I have complex Types as input (List) and output (Optional).
