### PR TITLE
#201: fixed 'order by' clause problems

### LINKED ISSUE #201: 'Order by' cause of Big Query adapter returns exception

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #201

### CODE REVIEW

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
+package com.exasol.adapter.dialects.bigquery;
+
+import com.exasol.adapter.*;
+import com.exasol.adapter.dialects.*;
+import com.exasol.adapter.sql.*;
+
+import java.util.*;
+
+public class BigQuerySqlGenerationVisitor extends SqlGenerationVisitor {
```
Comment (redcatbear) [inline jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]: JavaDoc is missing.

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+    public BigQuerySqlGenerationVisitor(final SqlDialect dialect, final SqlGenerationContext context) {
+        super(dialect, context);
+    }
+
+    @Override
+    public String visit(final SqlOrderBy orderBy) throws AdapterException {
+        final List<String> sqlOrderElement = new ArrayList<>();
+        for (int i = 0; i < orderBy.getExpressions().size(); ++i) {
+            String elementSql = orderBy.getExpressions().get(i).accept(this);
+            final boolean isAscending = orderBy.isAscending().get(i);
```
Comment (redcatbear) [inline jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]: move up one line

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+public class BigQuerySqlGenerationVisitor extends SqlGenerationVisitor {
+    public BigQuerySqlGenerationVisitor(final SqlDialect dialect, final SqlGenerationContext context) {
+        super(dialect, context);
+    }
+
+    @Override
+    public String visit(final SqlOrderBy orderBy) throws AdapterException {
+        final List<String> sqlOrderElement = new ArrayList<>();
+        for (int i = 0; i < orderBy.getExpressions().size(); ++i) {
+            String elementSql = orderBy.getExpressions().get(i).accept(this);
```
Comment (redcatbear) [inline jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]: 1. Move down one line.
1. Make it final.
1. Replace the if with the `? ... : ...` notation.

File: jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitorTest.java [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+
+    @Test
+    void visit() throws AdapterException {
+        final SqlDialect dialect = new BigQuerySqlDialect(this.connection, AdapterProperties.emptyProperties());
+        final SqlGenerationVisitor visitor = new BigQuerySqlGenerationVisitor(dialect,
+                new SqlGenerationContext("catalog", "schema", false));
+        final TableMetadata clicksMeta = getClicksTableMetadata();
+        final SqlOrderBy orderBy = new SqlOrderBy(ImmutableList.of(new SqlColumn(0, clicksMeta.getColumns().get(0))),
+                ImmutableList.of(true), ImmutableList.of(true));
+        assertThat(visitor.visit(orderBy), equalTo("ORDER BY `USER_ID`"));
```
Comment (redcatbear) [inline jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitorTest.java]: Unit test for `DESC` case is missing.

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java (hunk 2 above)
Comment (AnastasiiaSergienko) [reply jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]: fixed

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java (hunk 3 above)
Comment (AnastasiiaSergienko) [reply jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]: Can't fe final. because we change it later

Comment (AnastasiiaSergienko) [reply jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]: fixed

File: jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriterTest.java [hunk 5]
```diff
@@ -109,6 +108,20 @@ void testRewriteWithVarcharValues(final String columnName, final int type, final
...
+    void testRewriteWithStringValues(final String columnName, final int type, final String columnValue, final String resultValue)
+          throws AdapterException, SQLException {
+        when(this.mockResultSetMetaData.getColumnName(1)).thenReturn(columnName);
+        when(this.mockResultSet.getString(columnName)).thenReturn(columnValue);
+        when(this.mockResultSetMetaData.getColumnType(1)).thenReturn(type);
+        when(this.mockResultSetMetaData.getColumnCount()).thenReturn(1);
+        when(this.mockResultSet.next()).thenReturn(true, false);
+        assertThat(this.queryRewriter.rewrite(this.statement, this.exaMetadata, AdapterProperties.emptyProperties()),
+              equalTo("SELECT * FROM VALUES ('" + resultValue + "')"));
+    }
```
Comment (redcatbear) [inline jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/bigquery/BigQueryQueryRewriterTest.java]: :+1: nice

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java [hunk 6]
```diff
@@ -0,0 +1,33 @@
+package com.exasol.adapter.dialects.bigquery;
+
+import com.exasol.adapter.*;
+import com.exasol.adapter.dialects.*;
+import com.exasol.adapter.sql.*;
+
+import java.util.*;
+
+/**
+ * this class implements {@link BigQuerySqlDialect} specific logic of SQL Generation Visitor.
```
Comment (redcatbear) [inline jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]:
```suggestion
 * This class implements a Google-Big-Query-specific variant of a SQL generation visitor.
```

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java (hunk 1 above)
Comment (AnastasiiaSergienko) [reply jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]: fixed

File: jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java (hunk 6 above)
Comment (AnastasiiaSergienko) [reply jdbc-adapter/virtualschema-jdbc-adapter/src/main/java/com/exasol/adapter/dialects/bigquery/BigQuerySqlGenerationVisitor.java]: fixed
